travis:
  secure:
    BINSTAR_TOKEN: SlsPntSPx3Gufe2DlPzuiCFs2vkqbCiHrvn3xyKU0HsXbapzuiycHPVplyMF7iaYEmxv0ZaV+DGMQJJu8rAnjwELntUxRQ+PYavjm6l8y7eTjP0YwKud9rR4Akm4l23XZ92IQszEwrBFzKYXPHqfA9sSHCZLS3k7CfUqAvi2uTR2O+MArDlKk7YAm5EnUbJuPujgFIBfIzWD7KL/LkGZxOvHECyDTPqXWiI5Da6hwco5SoOjevB4pKEdCQZ4u8l7slyycZoOpIA6h3ADiuW8y+nbsfoflXNGV//nYg7w0R9oEf1WBb4D73gtauK4IjIq+fcBfG5zDL/I/f0tQRltBRaKduDOYpnZJ4IJ0cfs+4ghTC1s1J7cqWCjftRXTxqVQKudj/0ujGcZpIOAxvEHzJHLy8+B5OPf6e3W2ny4cnIFDDZrL9p/DK2jzuZJKJIu1OaTX4xb1wdd/azAU8QEDtephx7E2P8IE45ZHrKF4JKTx30nttEvyyCIZeG3jZUYXlfecwdN3OjL3qliSFGBr4+JN8llKOh50JMY2qqqXvWsrv8teg6BJOFs/RAPMY8X4vD6jHd3CZSUGDCO5pJetpIfTz336NL7tCSaI2GEg5n5eIpn09wwWwJABWyxTMKXAg5cZYfmZN0eVZkr9y0tRbYQiMrLyArZpQ9t5uv2it4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
